# Generated by Django 4.0.6 on 2022-07-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='movie',
            new_name='movies',
        ),
    ]
